(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]]


(* ::Input::Initialization:: *)
<<match2fit`


(* ::Input::Initialization:: *)
realDiagSMYukas={yu[i_,j_]:>KroneckerDelta[i,j]*(KroneckerDelta[j,1]yu[1,1]+KroneckerDelta[j,2]yu[2,2]+KroneckerDelta[j,3]yu[3,3]),yd[i_,j_]:>(KroneckerDelta[j,1]*KroneckerDelta[i,1]*yd[1,1]+KroneckerDelta[j,2]*KroneckerDelta[i,2]*yd[2,2]+KroneckerDelta[j,3]*KroneckerDelta[i,3]*yd[3,3]),yl[i_,j_]:>KroneckerDelta[i,j]*(KroneckerDelta[j,1]yl[1,1]+KroneckerDelta[j,2]yl[2,2]+KroneckerDelta[j,3]yl[3,3]),
yubar[i_,j_]:>KroneckerDelta[i,j]*(KroneckerDelta[j,1]yu[1,1]+KroneckerDelta[j,2]yu[2,2]+KroneckerDelta[j,3]yu[3,3]),
ydbar[i_,j_]:>KroneckerDelta[i,j]*(KroneckerDelta[j,1]yd[1,1]+KroneckerDelta[j,2]yd[2,2]+KroneckerDelta[j,3]yd[3,3]),
ylbar[i_,j_]:>KroneckerDelta[i,j]*(KroneckerDelta[j,1]yl[1,1]+KroneckerDelta[j,2]yl[2,2]+KroneckerDelta[j,3]yl[3,3])};



